#!/usr/bin/env bash
# Copyright 2026 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0
#
# Assembles the publishable presentations site into an output directory:
#   - copies every *.html / *.css from this folder into the output dir
#   - generates index.html linking each presentation, using its <title> as link text
#
# Repo-only files (this script, README.md) are never copied, so they don't reach the site.
#
# Usage: build-index.sh [output-dir]   (default: ./_site)

set -euo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${1:-_site}"

mkdir -p "$OUT_DIR"
shopt -s nullglob

# Copy presentation assets (html + css) into the output dir.
for f in "$SRC_DIR"/*.html "$SRC_DIR"/*.css; do
  [ "$(basename "$f")" = "index.html" ] && continue
  cp "$f" "$OUT_DIR"/
done

# Extract the first <title>…</title> text from an HTML file (fallback: filename).
extract_title() {
  local file="$1" title
  title="$(tr '\n' ' ' < "$file" \
    | grep -oiE '<title>[^<]*</title>' \
    | head -n1 \
    | sed -E 's/<[^>]+>//g' \
    | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
  if [ -z "$title" ]; then
    title="$(basename "$file" .html)"
  fi
  printf '%s' "$title"
}

# HTML-escape text for safe interpolation into the generated page.
escape() {
  printf '%s' "$1" \
    | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/"/\&quot;/g'
}

# Build the list of presentation cards.
cards=""
count=0
for f in "$SRC_DIR"/*.html; do
  name="$(basename "$f")"
  [ "$name" = "index.html" ] && continue
  title="$(escape "$(extract_title "$f")")"
  cards="${cards}      <li><a class=\"card\" href=\"${name}\"><span class=\"card-title\">${title}</span><span class=\"card-file\">${name}</span></a></li>
"
  count=$((count + 1))
done

if [ "$count" -eq 0 ]; then
  body='      <li class="empty">No presentations yet. Add an HTML file to <code>docs/presentations/</code> to see it listed here.</li>'
else
  body="$cards"
fi

cat > "$OUT_DIR/index.html" <<EOF
<!DOCTYPE html>
<!--
 Copyright 2026 NVIDIA CORPORATION
 SPDX-License-Identifier: Apache-2.0
 Generated by docs/presentations/build-index.sh — do not edit by hand.
-->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>KAI Scheduler — Design Presentations</title>
  <style>
    :root {
      --bg:       #0d1117;
      --surface:  #161b22;
      --surface2: #21262d;
      --border:   #30363d;
      --text:     #e6edf3;
      --muted:    #8b949e;
      --accent:   #58a6ff;
      --radius:   6px;
    }
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background: var(--bg);
      color: var(--text);
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
      font-size: 14px;
      line-height: 1.5;
      min-height: 100vh;
    }
    .page-header {
      background: var(--surface);
      border-bottom: 1px solid var(--border);
      padding: 16px 24px;
    }
    .page-header h1 { font-size: 18px; font-weight: 600; }
    .page-header p { color: var(--muted); font-size: 13px; margin-top: 4px; }
    main { max-width: 860px; margin: 0 auto; padding: 24px; }
    ul { list-style: none; display: grid; gap: 12px; }
    .card {
      display: flex;
      flex-direction: column;
      gap: 4px;
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 16px 18px;
      text-decoration: none;
      color: var(--text);
      transition: border-color .15s ease, background .15s ease;
    }
    .card:hover { border-color: var(--accent); background: var(--surface2); }
    .card-title { font-size: 15px; font-weight: 600; color: var(--accent); }
    .card-file { font-size: 12px; color: var(--muted); font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
    .empty {
      color: var(--muted);
      background: var(--surface);
      border: 1px dashed var(--border);
      border-radius: var(--radius);
      padding: 24px;
      text-align: center;
    }
    .empty code { color: var(--text); }
  </style>
</head>
<body>
  <header class="page-header">
    <h1>KAI Scheduler — Design Presentations</h1>
    <p>Archived presentations of KAI Scheduler design documents.</p>
  </header>
  <main>
    <ul>
${body}
    </ul>
  </main>
</body>
</html>
EOF

echo "Wrote $OUT_DIR/index.html ($count presentation(s))."
